basePath: /
definitions:
  models.Client:
    properties:
      address:
        description: Endereço completo
        type: string
      city:
        description: Cidade do cliente
        type: string
      complement:
        description: Complemento do endereço
        type: string
      country:
        description: País do cliente
        type: string
      createdAt:
        type: string
      deletedAt:
        type: string
      id:
        type: integer
      latitude:
        description: Latitude da localização
        type: number
      longitude:
        description: Longitude da localização
        type: number
      name:
        description: Nome do cliente
        type: string
      neighborhood:
        description: Bairro do cliente
        type: string
      number:
        description: Número da residência
        type: integer
      state:
        description: Estado do cliente
        type: string
      street:
        description: Nome da rua
        type: string
      updatedAt:
        type: string
      weight_kg:
        description: Peso do cliente em kg
        type: number
    type: object
  models.ClientUpdate:
    properties:
      address:
        description: Endereço completo
        type: string
      city:
        description: Cidade do cliente
        type: string
      complement:
        description: Complemento do endereço
        type: string
      country:
        description: País do cliente
        type: string
      createdAt:
        type: string
      deletedAt:
        type: string
      id:
        description: ID do cliente, necessário para a atualização
        type: integer
      latitude:
        description: Latitude da localização
        type: number
      longitude:
        description: Longitude da localização
        type: number
      name:
        description: Nome do cliente
        type: string
      neighborhood:
        description: Bairro do cliente
        type: string
      number:
        description: Número da residência
        type: integer
      state:
        description: Estado do cliente
        type: string
      street:
        description: Nome da rua
        type: string
      updatedAt:
        type: string
      weight_kg:
        description: Peso do cliente em kg
        type: number
    type: object
host: localhost:8080
info:
  contact: {}
  description: API de exemplo com integração Swagger, oferecendo uma interface interativa
    para documentação e testes de endpoints. Esta API foi desenvolvida para ilustrar
    boas práticas de documentação, utilizando Swagger para facilitar a navegação e
    o entendimento das operações disponíveis, parâmetros de entrada, respostas e exemplos
    de uso. Indicada para desenvolvimento e demonstração de integração entre APIs
    e clientes.
  title: API - Golang Desafio Backend
  version: "1.0"
paths:
  /deliveries:
    delete:
      description: Exclui todos os clientes ou um cliente específico pelo ID.
      parameters:
      - description: Excluir todos os clientes (true para excluir todos os clientes)
        in: query
        name: deleteAll
        type: boolean
      - description: ID do cliente a ser excluído (se deleteAll não for especificado)
        in: query
        name: id
        type: integer
      responses:
        "200":
          description: Mensagem de sucesso
          schema:
            type: string
        "400":
          description: Parâmetros inválidos
          schema:
            type: string
        "500":
          description: Erro interno do servidor
          schema:
            type: string
      summary: Excluir clientes
      tags:
      - deliveries
    get:
      description: Retorna uma lista de clientes paginada, ou um cliente específico
        se o ID for fornecido, permitindo definir o limite, offset, cidade e ID.
      parameters:
      - description: ID do cliente para busca específica
        in: query
        name: id
        type: integer
      - default: 100
        description: Número máximo de clientes por página
        in: query
        name: limit
        type: integer
      - default: 0
        description: Número de registros a pular antes de começar a listar os clientes
        in: query
        name: offset
        type: integer
      - description: Cidade para filtrar os clientes
        in: query
        name: city
        type: string
      responses:
        "200":
          description: Dados da lista de clientes com metadados de paginação
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Erro ao buscar clientes
          schema:
            type: string
      summary: Busca clientes com paginação e filtros de cidade e ID
      tags:
      - deliveries
    post:
      consumes:
      - application/json
      description: Recebe um JSON contendo os dados de um cliente e insere o registro
        no sistema.
      parameters:
      - description: Dados do cliente para criação
        in: body
        name: client
        required: true
        schema:
          $ref: '#/definitions/models.Client'
      produces:
      - application/json
      responses:
        "200":
          description: Cliente criado com sucesso
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 'Requisição inválida: erro no corpo da requisição ou JSON malformado'
          schema:
            type: string
        "500":
          description: Erro ao criar cliente no banco de dados
          schema:
            type: string
      summary: Cria um novo cliente
      tags:
      - deliveries
    put:
      description: Modifica os dados de um cliente existente.
      parameters:
      - description: ID do cliente para busca específica
        in: query
        name: id
        type: integer
      - description: Cliente para atualizar
        in: body
        name: client
        required: true
        schema:
          $ref: '#/definitions/models.ClientUpdate'
      responses:
        "200":
          description: Resposta com os dados do cliente atualizado
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Corpo da requisição inválido
          schema:
            type: string
        "404":
          description: Cliente não encontrado
          schema:
            type: string
        "500":
          description: Erro ao atualizar cliente
          schema:
            type: string
      summary: Atualiza um cliente
      tags:
      - deliveries
  /deliveries/geoconding/search:
    get:
      description: Retorna as coordenadas geográficas (latitude e longitude) de um
        endereço fornecido.
      parameters:
      - description: Endereço a ser consultado
        in: query
        name: endereco
        required: true
        type: string
      responses:
        "200":
          description: Resposta com latitude e longitude do endereço
          schema:
            additionalProperties:
              type: number
            type: object
        "400":
          description: Parâmetro 'endereco' ausente ou inválido
          schema:
            type: string
        "500":
          description: Erro ao consultar a API de geocoding
          schema:
            type: string
      summary: Busca latitude e longitude de um endereço
      tags:
      - geocoding
swagger: "2.0"
